### ISSUE TITLE
Can't import PL variables of a ple in a ple 

### ISSUE THREAD

**Issue by nimdanor** [cisstech/platon#101] opened 2024-05-20 15:37 UTC
I need to import some variables to organise my code. 

I would like to write some thing like:
@extends local.ple
or 
@copycontent local.ple 
so that every variables defined in the local.ple is imported in the current ple.

Like what happens when extending.

**Comment by NewMeeh** [comment] 2024-05-21 09:09
The issue is about parsing the file `local.ple` because it needs and line break at the end of the file

**Comment by mciissee** [comment] 2024-08-31 15:08
Seems to be fixed with this commit :  https://github.com/cisstech/platon/commit/a3c79f9fe496859e6ed2e56bd51f24d3645dabdd

**Closed by mciissee** 2024-08-31 15:08 UTC
Labels: bug
